image: Visual Studio 2019

# prevent MSBuild from running
build: off

clone_script:
  - cmd: |
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      git checkout -qf %APPVEYOR_REPO_COMMIT%
      
test_script:
  - ps: .\test.ps1

after_test:
  - ps:
      $client=New-Object System.Net.WebClient
      Get-ChildItem -Path ([System.IO.Path]::Combine("Artifacts", "*.xml")) foreach {
        Write-Host "Uploading test result: $($_.Name)"
        $client.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($Env:APPVEYOR_JOB_ID)", $_.ToString())
      }