version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: mysql.dockerfile
      args:
        MYSQL_PWD: secret
        MYSQL_DB: myapp_test
  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
  test:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    links:
      - db
      - redis
    working_dir: \App
    volumes:
      - .:C:\App
    command: ['pwsh', '-file', 'test.ps1']